#数据库配置
db:
  host: 192.168.29.66
  port: 3306
  name: leke
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPR0AraoBRLbwWceKNxoKTCu/8bL+wyYA7yR3Dy/TVB60Nmqjab4LxOm5TbW+8eTsGvTS1IfZpHQXs5Bn0NmGqECAwEAAQ==
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: iD4bvYYEacoJiV50K8HC1mvwWw16PtHfmyZJAbtyEIMcXbXXZtWUrh8Jo+M1qAmIvjMSeh5XLqzgnWMgusnffg==
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&allowMultiQueries=true
    druid:
      filter-class-names: stat
      filters: stat,config
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
ftp:
  server:
    ip: 120.76.153.220
    port: 52151
    userName: ftpuser
    password: zhys%vVUUqy#igK3Ft?I
  alpha:
    save-path:
      qr-code: alpha/images/qrcode
#微信公众号配置
wechar:
    menu:
      #就诊记录
      diagnosisRecord: http%3A%2F%2Fjcyx18081.ebmsz.com%2Falpha%2Frecord.html
      #阿尔法医生
      alpha: http%3A%2F%2Fjcyx18081.ebmsz.com%2Falpha%2Falpha.html